### ISSUE TITLE
build fail because incompatible with freebsd

### ISSUE THREAD

**Issue by cjmt2** [MMOTutkunlari/AltyapiServer#5]
$ cd  ..db/src && gmake -j2
...

linking ../db_r40020 ...
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.so when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.a when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.so when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.a when searching for -lunwind
/usr/local/bin/ld: cannot find -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libssl.so when searching for -lssl
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libssl.a when searching for -lssl
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libcrypto.so when searching for -lcrypto
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libcrypto.a when searching for -lcrypto
/usr/local/bin/ld: skipping incompatible /usr/local/lib/gcc10/gcc/x86_64-portbld-freebsd13.0/10.2.0/../../../libstdc++.so when searching for -lstdc++
/usr/local/bin/ld: skipping incompatible /usr/local/lib/gcc10/gcc/x86_64-portbld-freebsd13.0/10.2.0/../../../libstdc++.a when searching for -lstdc++
/usr/local/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:56: ../db_r40020] Error 1
AltyapiServer@localhost:/usr/home/AltyapiServer/Srcs/Server/db/src $

$ cd  ..game/src && gmake -j2
linking ../game_r40020....
/usr/local/bin/ld: skipping incompatible ../../../Extern/lib/libcryptopp.a when searching for -lcryptopp
/usr/local/bin/ld: cannot find -lcryptopp
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.so when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.a when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.so when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.a when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.so when searching for -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libunwind.a when searching for -lunwind
/usr/local/bin/ld: cannot find -lunwind
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libssl.so when searching for -lssl
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libssl.a when searching for -lssl
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libssl.so when searching for -lssl
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libssl.a when searching for -lssl
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libcrypto.so when searching for -lcrypto
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libcrypto.a when searching for -lcrypto
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libcrypto.so when searching for -lcrypto
/usr/local/bin/ld: skipping incompatible /usr/local/lib/libcrypto.a when searching for -lcrypto
/usr/local/bin/ld: skipping incompatible /usr/local/lib/gcc10/gcc/x86_64-portbld-freebsd13.0/10.2.0/../../../libstdc++.so when searching for -lstdc++
/usr/local/bin/ld: skipping incompatible /usr/local/lib/gcc10/gcc/x86_64-portbld-freebsd13.0/10.2.0/../../../libstdc++.a when searching for -lstdc++
/usr/local/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:140: ../game_r40020] Error 1

 $ uname -a
FreeBSD localhost 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

**Comment by MMOTutkunlari** [comment]
Hello, you can only compile the source code in the freebsd 32-bit version.
